# Site Settings
title: Possel
email: meh@butts.so
description: "Possel - a better cross platform IRC client"
baseurl: "/static"
url: "http://butts.so"
author: "Possel"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /

# Build Settings
markdown: kramdown
permalink: pretty
